### DATA PROFILING & CLEANING

Step 1 — Check whether Drive is mounted

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Step 2 — Import required libraries

In [6]:
import pandas as pd
import numpy as np
import os

Step 3 — Find your project folder

In [8]:
PROJECT_PATH = "/content/drive/MyDrive/ADS-Airbnb-Project"

In [9]:
print(os.path.exists(PROJECT_PATH))

True

Step 4 — Define the dataset paths

In [10]:
RAW_DATA_PATH = os.path.join(
    PROJECT_PATH,
    "datasets",
    "raw"
)

PROCESSED_DATA_PATH = os.path.join(
    PROJECT_PATH,
    "datasets",
    "processed"
)

TABLE_PATH = os.path.join(
    PROJECT_PATH,
    "outputs",
    "tables"
)

VALIDATION_PATH = os.path.join(
    PROJECT_PATH,
    "outputs",
    "validation"
)

PROFILING_PATH = os.path.join(
    PROJECT_PATH,
    "outputs",
    "profiling"
)

Step 5 — Check your raw files

In [12]:
!ls -lh "$RAW_DATA_PATH"

total 15M
-rw------- 1 root root 6.3M Jun 23 21:00 calendar.csv
-rw------- 1 root root 1.4M Jun 23 21:00 listings.csv
-rw------- 1 root root 7.2M Jun 23 21:00 reviews.csv

Step 6 — Load the three datasets again

In [13]:
listings_df = pd.read_csv(
    os.path.join(
        RAW_DATA_PATH,
        "listings.csv"
    )
)

calendar_df = pd.read_csv(
    os.path.join(
        RAW_DATA_PATH,
        "calendar.csv"
    )
)

reviews_df = pd.read_csv(
    os.path.join(
        RAW_DATA_PATH,
        "reviews.csv"
    )
)

In [14]:
print(
    "Listings Dataset Shape:",
    listings_df.shape
)

print(
    "Calendar Dataset Shape:",
    calendar_df.shape
)

print(
    "Reviews Dataset Shape:",
    reviews_df.shape
)

Listings Dataset Shape: (490, 90)
Calendar Dataset Shape: (178850, 5)
Reviews Dataset Shape: (29046, 6)

Step 8 — IMPORTANT: recreate the cleaned copies

In [15]:
listings_clean = listings_df.copy()
calendar_clean = calendar_df.copy()
reviews_clean = reviews_df.copy()

In [16]:
print("Listings:", listings_clean.shape)
print("Calendar:", calendar_clean.shape)
print("Reviews :", reviews_clean.shape)

Listings: (490, 90)
Calendar: (178850, 5)
Reviews : (29046, 6)

Step 9 — Display all actual column names

In [17]:
print("========== LISTINGS COLUMNS ==========")

for i, col in enumerate(listings_clean.columns, start=1):
    print(i, ":", col)

print("\n========== CALENDAR COLUMNS ==========")

for i, col in enumerate(calendar_clean.columns, start=1):
    print(i, ":", col)

print("\n========== REVIEWS COLUMNS ==========")

for i, col in enumerate(reviews_clean.columns, start=1):
    print(i, ":", col)

========== LISTINGS COLUMNS ==========
1 : id
2 : listing_url
3 : scrape_id
4 : last_scraped
5 : source
6 : name
7 : description
8 : neighborhood_overview
9 : picture_url
10 : host_id
11 : host_url
12 : host_profile_id
13 : host_profile_url
14 : host_name
15 : host_since
16 : hosts_time_as_user_years
17 : hosts_time_as_user_months
18 : hosts_time_as_host_years
19 : hosts_time_as_host_months
20 : host_location
21 : host_about
22 : host_response_time
23 : host_response_rate
24 : host_acceptance_rate
25 : host_is_superhost
26 : host_thumbnail_url
27 : host_picture_url
28 : host_neighbourhood
29 : host_listings_count
30 : host_total_listings_count
31 : host_verifications
32 : host_has_profile_pic
33 : host_identity_verified
34 : neighbourhood
35 : neighbourhood_cleansed
36 : neighbourhood_group_cleansed
37 : latitude
38 : longitude
39 : property_type
40 : room_type
41 : accommodates
42 : bathrooms
43 : bathrooms_text
44 : bedrooms
45 : beds
46 : amenities
47 : price
48 : price_quote_checkin_date
49 : price_quote_checkout_date
50 : price_quote_total_price
51 : price_quote_price_per_night
52 : price_quote_raw
53 : minimum_nights
54 : maximum_nights
55 : minimum_minimum_nights
56 : maximum_minimum_nights
57 : minimum_maximum_nights
58 : maximum_maximum_nights
59 : minimum_nights_avg_ntm
60 : maximum_nights_avg_ntm
61 : calendar_updated
62 : has_availability
63 : availability_30
64 : availability_60
65 : availability_90
66 : availability_365
67 : calendar_last_scraped
68 : number_of_reviews
69 : number_of_reviews_ltm
70 : number_of_reviews_l30d
71 : availability_eoy
72 : number_of_reviews_ly
73 : estimated_occupancy_l365d
74 : estimated_revenue_l365d
75 : first_review
76 : last_review
77 : review_scores_rating
78 : review_scores_accuracy
79 : review_scores_cleanliness
80 : review_scores_checkin
81 : review_scores_communication
82 : review_scores_location
83 : review_scores_value
84 : license
85 : instant_bookable
86 : calculated_host_listings_count
87 : calculated_host_listings_count_entire_homes
88 : calculated_host_listings_count_private_rooms
89 : calculated_host_listings_count_shared_rooms
90 : reviews_per_month

========== CALENDAR COLUMNS ==========
1 : listing_id
2 : date
3 : available
4 : minimum_nights
5 : maximum_nights

========== REVIEWS COLUMNS ==========
1 : listing_id
2 : id
3 : date
4 : reviewer_id
5 : reviewer_name
6 : comments

In [19]:
def missing_report(df):
    report = pd.DataFrame({
        "Column": df.columns,
        "Missing_Count": df.isna().sum().values,
        "Missing_Percentage": (
            df.isna().mean().values * 100
        )
    })

    return report.sort_values(
        "Missing_Percentage",
        ascending=False
    )


listings_missing = missing_report(listings_clean)
calendar_missing = missing_report(calendar_clean)
reviews_missing = missing_report(reviews_clean)

print("========== LISTINGS ==========")
display(
    listings_missing[
        listings_missing["Missing_Count"] > 0
    ]
)

========== LISTINGS ==========

                          Column  Missing_Count  Missing_Percentage
7          neighborhood_overview            490          100.000000
14                    host_since            490          100.000000
21            host_response_time            490          100.000000
25            host_thumbnail_url            490          100.000000
23          host_acceptance_rate            490          100.000000
22            host_response_rate            490          100.000000
30            host_verifications            490          100.000000
33                 neighbourhood            490          100.000000
29     host_total_listings_count            490          100.000000
27            host_neighbourhood            490          100.000000
60              calendar_updated            490          100.000000
84              instant_bookable            490          100.000000
83                       license            490          100.000000
35  neighbourhood_group_cleansed            490          100.000000
20                    host_about            230           46.938776
19                 host_location            142           28.979592
43                      bedrooms            112           22.857143
78     review_scores_cleanliness             60           12.244898
77        review_scores_accuracy             60           12.244898
74                  first_review             60           12.244898
79         review_scores_checkin             60           12.244898
76          review_scores_rating             60           12.244898
89             reviews_per_month             60           12.244898
82           review_scores_value             60           12.244898
80   review_scores_communication             60           12.244898
81        review_scores_location             60           12.244898
75                   last_review             60           12.244898
41                     bathrooms             45            9.183673
44                          beds             44            8.979592
46                         price             32            6.530612
50   price_quote_price_per_night             32            6.530612
49       price_quote_total_price             32            6.530612
73       estimated_revenue_l365d             32            6.530612
51               price_quote_raw             22            4.489796
48     price_quote_checkout_date             22            4.489796
47      price_quote_checkin_date             22            4.489796
6                    description              9            1.836735
61              has_availability              5            1.020408
42                bathrooms_text              4            0.816327
53                maximum_nights              1            0.204082
56        minimum_maximum_nights              1            0.204082
54        minimum_minimum_nights              1            0.204082
55        maximum_minimum_nights              1            0.204082
52                minimum_nights              1            0.204082
57        maximum_maximum_nights              1            0.204082

In [20]:
print("========== CALENDAR ==========")

display(
    calendar_missing[
        calendar_missing["Missing_Count"] > 0
    ]
)

print("========== REVIEWS ==========")

display(
    reviews_missing[
        reviews_missing["Missing_Count"] > 0
    ]
)

========== CALENDAR ==========

Empty DataFrame
Columns: [Column, Missing_Count, Missing_Percentage]
Index: []

========== REVIEWS ==========

     Column  Missing_Count  Missing_Percentage
5  comments              8            0.027543

Step 10 — Check duplicates

In [21]:
print("Listings duplicates:",
      listings_clean.duplicated().sum())

print("Calendar duplicates:",
      calendar_clean.duplicated().sum())

print("Reviews duplicates:",
      reviews_clean.duplicated().sum())

Listings duplicates: 0
Calendar duplicates: 0
Reviews duplicates: 0

In [22]:
listings_clean = listings_clean.drop_duplicates().copy()
calendar_clean = calendar_clean.drop_duplicates().copy()
reviews_clean = reviews_clean.drop_duplicates().copy()

print("\nAfter duplicate removal:")

print("Listings:", listings_clean.shape)
print("Calendar:", calendar_clean.shape)
print("Reviews :", reviews_clean.shape)

After duplicate removal:
Listings: (490, 90)
Calendar: (178850, 5)
Reviews : (29046, 6)

Step 11 — Identify numeric and categorical columns

In [23]:
print("========== LISTINGS DATA TYPES ==========")

print(
    listings_clean.dtypes.value_counts()
)

print("\n========== NUMERIC COLUMNS ==========")

numeric_columns = listings_clean.select_dtypes(
    include=np.number
).columns.tolist()

print(numeric_columns)

print("\nNumber of numeric columns:",
      len(numeric_columns))

print("\n========== CATEGORICAL COLUMNS ==========")

categorical_columns = listings_clean.select_dtypes(
    include="object"
).columns.tolist()

print(categorical_columns)

print("\nNumber of categorical columns:",
      len(categorical_columns))

========== LISTINGS DATA TYPES ==========
float64    38
object     28
int64      24
Name: count, dtype: int64

========== NUMERIC COLUMNS ==========
['id', 'scrape_id', 'neighborhood_overview', 'host_id', 'host_profile_id', 'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months', 'hosts_time_as_host_years', 'hosts_time_as_host_months', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_thumbnail_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'neighbourhood', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price_quote_total_price', 'price_quote_price_per_night', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month']

Number of numeric columns: 62

========== CATEGORICAL COLUMNS ==========
['listing_url', 'last_scraped', 'source', 'name', 'description', 'picture_url', 'host_url', 'host_profile_url', 'host_name', 'host_location', 'host_about', 'host_is_superhost', 'host_picture_url', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood_cleansed', 'property_type', 'room_type', 'bathrooms_text', 'amenities', 'price', 'price_quote_checkin_date', 'price_quote_checkout_date', 'price_quote_raw', 'has_availability', 'calendar_last_scraped', 'first_review', 'last_review']

Number of categorical columns: 28

Step 12 — Check important Airbnb columns

In [24]:
important_columns = [
    "id",
    "listing_id",
    "price",
    "room_type",
    "property_type",
    "accommodates",
    "bedrooms",
    "beds",
    "bathrooms",
    "host_since",
    "host_is_superhost",
    "instant_bookable",
    "amenities",
    "availability_365"
]

print("Column availability:\n")

for col in important_columns:

    if col in listings_clean.columns:
        print("✓", col)

    else:
        print("✗", col, "(not found)")

Column availability:

✓ id
✗ listing_id (not found)
✓ price
✓ room_type
✓ property_type
✓ accommodates
✓ bedrooms
✓ beds
✓ bathrooms
✓ host_since
✓ host_is_superhost
✓ instant_bookable
✓ amenities
✓ availability_365

Step 13 — Clean IDs

In [25]:
print("Listings ID examples:")

if "id" in listings_clean.columns:
    display(listings_clean[["id"]].head())

if "listing_id" in listings_clean.columns:
    display(listings_clean[["listing_id"]].head())

print("\nCalendar ID examples:")

if "listing_id" in calendar_clean.columns:
    display(calendar_clean[["listing_id"]].head())

print("\nReviews ID examples:")

if "listing_id" in reviews_clean.columns:
    display(reviews_clean[["listing_id"]].head())

Listings ID examples:

        id
0  2992450
1  3820211
2  5651579
3  6623339
4  9501054

Calendar ID examples:

   listing_id
0     2992450
1     2992450
2     2992450
3     2992450
4     2992450

Reviews ID examples:

   listing_id
0     2992450
1     2992450
2     2992450
3     2992450
4     2992450

Step 8 — Standardize Listings ID

In [26]:
if "id" in listings_clean.columns:

    listings_clean["id"] = pd.to_numeric(
        listings_clean["id"],
        errors="coerce"
    )

    listings_clean = listings_clean[
        listings_clean["id"].notna()
    ].copy()

    listings_clean["id"] = (
        listings_clean["id"].astype("int64")
    )

In [27]:
if "id" in listings_clean.columns:

    listings_clean = listings_clean.rename(
        columns={
            "id": "listing_id"
        }
    )

In [28]:
print(
    "Listings ID unique:",
    listings_clean["listing_id"].nunique()
)

print(
    "Listings rows:",
    len(listings_clean)
)

Listings ID unique: 490
Listings rows: 490

Step 14 — Clean Calendar

In [29]:
if "date" in calendar_clean.columns:

    calendar_clean["date"] = pd.to_datetime(
        calendar_clean["date"],
        errors="coerce"
    )

In [30]:
if "listing_id" in calendar_clean.columns:

    calendar_clean["listing_id"] = pd.to_numeric(
        calendar_clean["listing_id"],
        errors="coerce"
    )

In [31]:
calendar_clean = calendar_clean[
    calendar_clean["listing_id"].notna()
].copy()

calendar_clean["listing_id"] = (
    calendar_clean["listing_id"].astype("int64")
)

Step 15 - Clean Calendar Price

In [32]:
if "price" in calendar_clean.columns:

    calendar_clean["price"] = (
        calendar_clean["price"]
        .astype(str)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    calendar_clean["price"] = pd.to_numeric(
        calendar_clean["price"],
        errors="coerce"
    )

Step 16 — Clean Calendar Availability

In [36]:
print(
    calendar_clean["available"]
    .value_counts(dropna=False)
)

available
t    119018
f     59832
Name: count, dtype: int64

In [37]:
calendar_clean["available"] = (
    calendar_clean["available"]
    .astype(str)
    .str.lower()
    .map({
        "t": 1,
        "f": 0,
        "true": 1,
        "false": 0
    })
)

In [38]:
print(
    calendar_clean["available"]
    .value_counts(dropna=False)
)

available
1    119018
0     59832
Name: count, dtype: int64

Step 17 — Clean Reviews

In [39]:
if "date" in reviews_clean.columns:

    reviews_clean["date"] = pd.to_datetime(
        reviews_clean["date"],
        errors="coerce"
    )

In [40]:
if "listing_id" in reviews_clean.columns:

    reviews_clean["listing_id"] = pd.to_numeric(
        reviews_clean["listing_id"],
        errors="coerce"
    )

    reviews_clean = reviews_clean[
        reviews_clean["listing_id"].notna()
    ].copy()

    reviews_clean["listing_id"] = (
        reviews_clean["listing_id"].astype("int64")
    )

Step 18 — Save the three cleaned intermediate datasets

In [42]:
listings_clean.to_csv(
    os.path.join(
        PROCESSED_DATA_PATH,
        "listings_cleaned.csv"
    ),
    index=False
)

calendar_clean.to_csv(
    os.path.join(
        PROCESSED_DATA_PATH,
        "calendar_cleaned.csv"
    ),
    index=False
)

reviews_clean.to_csv(
    os.path.join(
        PROCESSED_DATA_PATH,
        "reviews_cleaned.csv"
    ),
    index=False
)

print("Intermediate cleaned datasets saved successfully.")

Intermediate cleaned datasets saved successfully.

Step 19 — Check the cleaned datasets

In [43]:
print("========== FINAL CLEANING CHECK ==========")

print(
    "Listings:",
    listings_clean.shape,
    "| Unique IDs:",
    listings_clean["listing_id"].nunique()
)

print(
    "Calendar:",
    calendar_clean.shape,
    "| Unique IDs:",
    calendar_clean["listing_id"].nunique()
)

print(
    "Reviews:",
    reviews_clean.shape,
    "| Unique IDs:",
    reviews_clean["listing_id"].nunique()
)

========== FINAL CLEANING CHECK ==========
Listings: (490, 90) | Unique IDs: 490
Calendar: (178850, 5) | Unique IDs: 490
Reviews: (29046, 6) | Unique IDs: 430

In [44]:
for i, col in enumerate(listings_clean.columns, start=1):
    print(i, ":", col)

1 : listing_id
2 : listing_url
3 : scrape_id
4 : last_scraped
5 : source
6 : name
7 : description
8 : neighborhood_overview
9 : picture_url
10 : host_id
11 : host_url
12 : host_profile_id
13 : host_profile_url
14 : host_name
15 : host_since
16 : hosts_time_as_user_years
17 : hosts_time_as_user_months
18 : hosts_time_as_host_years
19 : hosts_time_as_host_months
20 : host_location
21 : host_about
22 : host_response_time
23 : host_response_rate
24 : host_acceptance_rate
25 : host_is_superhost
26 : host_thumbnail_url
27 : host_picture_url
28 : host_neighbourhood
29 : host_listings_count
30 : host_total_listings_count
31 : host_verifications
32 : host_has_profile_pic
33 : host_identity_verified
34 : neighbourhood
35 : neighbourhood_cleansed
36 : neighbourhood_group_cleansed
37 : latitude
38 : longitude
39 : property_type
40 : room_type
41 : accommodates
42 : bathrooms
43 : bathrooms_text
44 : bedrooms
45 : beds
46 : amenities
47 : price
48 : price_quote_checkin_date
49 : price_quote_checkout_date
50 : price_quote_total_price
51 : price_quote_price_per_night
52 : price_quote_raw
53 : minimum_nights
54 : maximum_nights
55 : minimum_minimum_nights
56 : maximum_minimum_nights
57 : minimum_maximum_nights
58 : maximum_maximum_nights
59 : minimum_nights_avg_ntm
60 : maximum_nights_avg_ntm
61 : calendar_updated
62 : has_availability
63 : availability_30
64 : availability_60
65 : availability_90
66 : availability_365
67 : calendar_last_scraped
68 : number_of_reviews
69 : number_of_reviews_ltm
70 : number_of_reviews_l30d
71 : availability_eoy
72 : number_of_reviews_ly
73 : estimated_occupancy_l365d
74 : estimated_revenue_l365d
75 : first_review
76 : last_review
77 : review_scores_rating
78 : review_scores_accuracy
79 : review_scores_cleanliness
80 : review_scores_checkin
81 : review_scores_communication
82 : review_scores_location
83 : review_scores_value
84 : license
85 : instant_bookable
86 : calculated_host_listings_count
87 : calculated_host_listings_count_entire_homes
88 : calculated_host_listings_count_private_rooms
89 : calculated_host_listings_count_shared_rooms
90 : reviews_per_month

## Feature Engineering

LISTING

Step 1 First verify the key columns

In [45]:
# Check important columns available in Listings

required_listing_columns = [
    "id",
    "host_id",
    "host_since",
    "host_response_rate",
    "host_acceptance_rate",
    "host_is_superhost",
    "neighbourhood",
    "neighbourhood_cleansed",
    "property_type",
    "room_type",
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "amenities",
    "price",
    "minimum_nights",
    "maximum_nights",
    "availability_365",
    "number_of_reviews",
    "review_scores_rating",
    "instant_bookable"
]

print("COLUMN AVAILABILITY")
print("=" * 60)

for col in required_listing_columns:
    if col in listings_clean.columns:
        print("✓", col)
    else:
        print("✗", col, "NOT FOUND")

COLUMN AVAILABILITY
============================================================
✗ id NOT FOUND
✓ host_id
✓ host_since
✓ host_response_rate
✓ host_acceptance_rate
✓ host_is_superhost
✓ neighbourhood
✓ neighbourhood_cleansed
✓ property_type
✓ room_type
✓ accommodates
✓ bathrooms
✓ bedrooms
✓ beds
✓ amenities
✓ price
✓ minimum_nights
✓ maximum_nights
✓ availability_365
✓ number_of_reviews
✓ review_scores_rating
✓ instant_bookable

In [47]:
print("First 31 Listings columns:")
for i, col in enumerate(listings_clean.columns[:31], start=1):
    print(i, ":", col)

First 31 Listings columns:
1 : listing_id
2 : listing_url
3 : scrape_id
4 : last_scraped
5 : source
6 : name
7 : description
8 : neighborhood_overview
9 : picture_url
10 : host_id
11 : host_url
12 : host_profile_id
13 : host_profile_url
14 : host_name
15 : host_since
16 : hosts_time_as_user_years
17 : hosts_time_as_user_months
18 : hosts_time_as_host_years
19 : hosts_time_as_host_months
20 : host_location
21 : host_about
22 : host_response_time
23 : host_response_rate
24 : host_acceptance_rate
25 : host_is_superhost
26 : host_thumbnail_url
27 : host_picture_url
28 : host_neighbourhood
29 : host_listings_count
30 : host_total_listings_count
31 : host_verifications

In [48]:
print("\nColumns containing 'id':")

for col in listings_clean.columns:
    if "id" in col.lower():
        print(col)

Columns containing 'id':
listing_id
scrape_id
host_id
host_profile_id
host_identity_verified

In [49]:
print("CALENDAR COLUMNS")
print("=" * 50)

for i, col in enumerate(calendar_clean.columns, start=1):
    print(i, ":", col)

CALENDAR COLUMNS
==================================================
1 : listing_id
2 : date
3 : available
4 : minimum_nights
5 : maximum_nights

In [50]:
print("\nREVIEWS COLUMNS")
print("=" * 50)

for i, col in enumerate(reviews_clean.columns, start=1):
    print(i, ":", col)

REVIEWS COLUMNS
==================================================
1 : listing_id
2 : id
3 : date
4 : reviewer_id
5 : reviewer_name
6 : comments

In [51]:
print("LISTINGS ID-LIKE COLUMNS")

for col in listings_clean.columns:
    if "id" in col.lower():
        print(
            f"\n{col}:"
        )
        print(
            listings_clean[col].head().tolist()
        )

LISTINGS ID-LIKE COLUMNS

listing_id:
[2992450, 3820211, 5651579, 6623339, 9501054]

scrape_id:
[20260616211424, 20260616211424, 20260616211424, 20260616211424, 20260616211424]

host_id:
[4621559, 19648678, 29288920, 19648678, 29288920]

host_profile_id:
[1462661762635155041, 1463087024016718788, 1465431505328745177, 1463087024016718788, 1465431505328745177]

host_identity_verified:
['t', 't', 't', 't', 't']

In [52]:
print("\nCALENDAR listing_id sample:")

if "listing_id" in calendar_clean.columns:
    print(
        calendar_clean["listing_id"].head().tolist()
    )

print("\nREVIEWS listing_id sample:")

if "listing_id" in reviews_clean.columns:
    print(
        reviews_clean["listing_id"].head().tolist()
    )

CALENDAR listing_id sample:
[2992450, 2992450, 2992450, 2992450, 2992450]

REVIEWS listing_id sample:
[2992450, 2992450, 2992450, 2992450, 2992450]

Step 2 Create working copy

In [55]:
# Create a fresh working copy after cleaning

listings_fe = listings_clean.copy()

print("Listings shape:", listings_fe.shape)

Listings shape: (490, 90)

Step 3: Convert important numerical columns

In [56]:
numeric_features = [
    "accommodates",
    "bathrooms",
    "bedrooms",
    "beds",
    "minimum_nights",
    "maximum_nights",
    "availability_30",
    "availability_60",
    "availability_90",
    "availability_365",
    "number_of_reviews",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "review_scores_rating",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "reviews_per_month",
    "estimated_occupancy_l365d",
    "estimated_revenue_l365d"
]

for col in numeric_features:
    if col in listings_fe.columns:
        listings_fe[col] = pd.to_numeric(
            listings_fe[col],
            errors="coerce"
        )

print("Numeric conversion completed.")

Numeric conversion completed.

Step 4: Feature  1 — Amenity Count

In [57]:
listings_fe["amenity_count"] = (
    listings_fe["amenities"]
    .fillna("")
    .astype(str)
    .str.count(",")
)

listings_fe["amenity_count"] = np.where(
    listings_fe["amenities"]
    .fillna("")
    .str.strip()
    .eq(""),
    0,
    listings_fe["amenity_count"] + 1
)

In [58]:
display(
    listings_fe[
        ["amenities", "amenity_count"]
    ].head()
)

                                           amenities  amenity_count
0  ["Kitchen", "Essentials", "Heating", "Wifi", "...              8
1  ["Free washer \u2013 In unit", "Microwave", "S...             33
2  ["Free washer \u2013 In unit", "Microwave", "S...             40
3  ["Microwave", "Stove", "Shower gel", "Coffee",...             43
4  ["Microwave", "Shower gel", "Long term stays a...             28

In [62]:
print(
    listings_fe["availability_ratio"].describe()
)

count    490.000000
mean       0.665463
std        0.319454
min        0.000000
25%        0.450685
50%        0.779452
75%        0.952740
max        1.000000
Name: availability_ratio, dtype: float64

Step 5: Feature 2 — Entire Home Indicator

In [63]:
listings_fe["is_entire_home"] = (
    listings_fe["room_type"]
    .astype(str)
    .str.lower()
    .eq("entire home/apt")
    .astype(int)
)

In [64]:
print(
    listings_fe["is_entire_home"].value_counts()
)

is_entire_home
1    345
0    145
Name: count, dtype: int64

Step 6: Feature 3 - Superhost Indicator

In [65]:
listings_fe["is_superhost"] = (
    listings_fe["host_is_superhost"]
    .astype(str)
    .str.lower()
    .map({
        "t": 1,
        "f": 0,
        "true": 1,
        "false": 0
    })
)

In [66]:
print(
    listings_fe["is_superhost"].value_counts(
        dropna=False
    )
)

is_superhost
0    275
1    215
Name: count, dtype: int64

Step 7: Feature 4 — host_listing_count

In [114]:
print(
    listings_clean["calculated_host_listings_count"]
    .value_counts(dropna=False)
    .head(10)
)

calculated_host_listings_count
1     107
2      72
3      42
8      40
11     33
16     32
29     29
6      24
21     21
4      20
Name: count, dtype: int64

In [115]:
listings_fe["host_listing_count"] = pd.to_numeric(
    listings_clean["calculated_host_listings_count"],
    errors="coerce"
).fillna(0)

Step 8: Feature 5 — Bathroom/Bedroom Ratio

In [67]:
listings_fe["bathroom_bedroom_ratio"] = (
    listings_fe["bathrooms"] /
    listings_fe["bedrooms"].replace(
        0,
        np.nan
    )
)

In [68]:
display(
    listings_fe[
        [
            "bathrooms",
            "bedrooms",
            "bathroom_bedroom_ratio"
        ]
    ].head()
)

   bathrooms  bedrooms  bathroom_bedroom_ratio
0        1.0       2.0                     0.5
1        1.0       1.0                     1.0
2        1.0       NaN                     NaN
3        1.0       1.0                     1.0
4        1.0       NaN                     NaN

Step 15 — Save the feature-engineered Listings dataset

In [117]:
selected_listing_features = [
    "amenity_count",
    "is_entire_home",
    "is_superhost",
    "host_listing_count",
    "bathroom_bedroom_ratio"
]

In [118]:
listings_fe["bathroom_bedroom_ratio"] = (
    pd.to_numeric(listings_clean["bathrooms"], errors="coerce")
    /
    pd.to_numeric(listings_clean["bedrooms"], errors="coerce")
    .replace(0, np.nan)
).fillna(0)

In [119]:
listings_final = listings_clean.copy()

for feature in selected_listing_features:
    listings_final[feature] = listings_fe[feature]

print("FINAL LISTINGS FEATURES")
print("=" * 60)

display(
    listings_final[selected_listing_features].head(10)
)

FINAL LISTINGS FEATURES
============================================================

,amenity_count,is_entire_home,is_superhost,host_listing_count,bathroom_bedroom_ratio
0,8,1,0,1,0.500000
1,33,1,1,7,1.000000
2,40,1,0,2,0.000000
3,43,1,1,7,1.000000
4,28,0,0,2,0.000000
5,23,0,1,2,0.000000
6,86,1,1,8,0.666667
7,28,0,0,2,0.000000
8,45,0,0,2,0.000000
9,55,1,0,1,0.500000

In [ ]:
print("Missing values in final features:")
print("=" * 60)

print(
    listings_final[
        selected_listing_features
    ].isna().sum()
)

CALENDAR

In [92]:
print("Possible ID columns:")
print([
    col for col in calendar_clean.columns
    if "id" in str(col).lower()
])

print("\nPossible price columns:")
print([
    col for col in calendar_clean.columns
    if "price" in str(col).lower()
])

print("\nPossible availability columns:")
print([
    col for col in calendar_clean.columns
    if "avail" in str(col).lower()
])

print("\nPossible nights columns:")
print([
    col for col in calendar_clean.columns
    if "night" in str(col).lower()
])

Possible ID columns:
['listing_id']

Possible price columns:
[]

Possible availability columns:
['available']

Possible nights columns:
['minimum_nights', 'maximum_nights']

In [93]:
# Create a fresh copy
calendar_fe = calendar_clean.copy()

# Convert minimum and maximum nights to numeric
calendar_fe["minimum_nights"] = pd.to_numeric(
    calendar_fe["minimum_nights"],
    errors="coerce"
)

calendar_fe["maximum_nights"] = pd.to_numeric(
    calendar_fe["maximum_nights"],
    errors="coerce"
)

# Convert availability to 0/1
calendar_fe["available_numeric"] = (
    calendar_fe["available"]
    .astype(str)
    .str.lower()
    .str.strip()
    .map({
        "t": 1,
        "f": 0,
        "true": 1,
        "false": 0
    })
)

print("Calendar preparation completed.")

print("\nAvailability values:")
print(calendar_fe["available"].value_counts(dropna=False))

print("\nMissing converted availability:")
print(calendar_fe["available_numeric"].isna().sum())

Calendar preparation completed.

Availability values:
available
1    119018
0     59832
Name: count, dtype: int64

Missing converted availability:
178850

In [85]:
print(calendar_clean.columns.tolist())

['listing_id', 'date', 'available', 'minimum_nights', 'maximum_nights']

In [ ]:
print("CALENDAR DATASET")
print("=" * 60)

print("Shape:", calendar_clean.shape)

print("\nColumns:")
for i, col in enumerate(calendar_clean.columns):
    print(i, ":", repr(col))

print("\nFirst 5 rows:")
display(calendar_clean.head())

print("\nData types:")
display(calendar_clean.dtypes)

Calendar Feature 1: Availability Rate

In [94]:
calendar_availability_rate = (
    calendar_fe
    .groupby("listing_id")["available_numeric"]
    .mean()
    .reset_index(name="calendar_availability_rate")
)

Calendar Feature 2: Available Days

In [95]:
calendar_available_days = (
    calendar_fe
    .groupby("listing_id")["available_numeric"]
    .sum()
    .reset_index(name="calendar_available_days")
)

Calendar Feature 3: Average Minimum Nights

In [96]:
calendar_avg_minimum_nights = (
    calendar_fe
    .groupby("listing_id")["minimum_nights"]
    .mean()
    .reset_index(name="calendar_avg_minimum_nights")
)

Calendar Feature 4: Average Maximum Nights

In [97]:

calendar_avg_maximum_nights = (
    calendar_fe
    .groupby("listing_id")["maximum_nights"]
    .mean()
    .reset_index(name="calendar_avg_maximum_nights")
)

Calendar Feature 5: Observation Count

In [98]:
calendar_observation_count = (
    calendar_fe
    .groupby("listing_id")
    .size()
    .reset_index(name="calendar_observation_count")
)

Combine all 5

In [99]:
calendar_features = calendar_availability_rate.merge(
    calendar_available_days,
    on="listing_id",
    how="outer"
)

calendar_features = calendar_features.merge(
    calendar_avg_minimum_nights,
    on="listing_id",
    how="outer"
)

calendar_features = calendar_features.merge(
    calendar_avg_maximum_nights,
    on="listing_id",
    how="outer"
)

calendar_features = calendar_features.merge(
    calendar_observation_count,
    on="listing_id",
    how="outer"
)

print("Calendar feature dataset shape:")
print(calendar_features.shape)

display(calendar_features.head(10))

Calendar feature dataset shape:
(490, 6)

,listing_id,calendar_availability_rate,calendar_available_days,calendar_avg_minimum_nights,calendar_avg_maximum_nights,calendar_observation_count
0,2992450,NaN,0.0,28.000000,1125.0,365
1,3820211,NaN,0.0,2.728767,1125.0,365
2,5651579,NaN,0.0,1.284932,1125.0,365
3,6623339,NaN,0.0,2.728767,1125.0,365
4,9501054,NaN,0.0,1.000000,1125.0,365
5,10768745,NaN,0.0,1.000000,1125.0,365
6,11253948,NaN,0.0,1.284932,1124.0,365
7,11639446,NaN,0.0,15.000000,112.0,365
8,12799126,NaN,0.0,5.000000,300.0,365
9,13083497,NaN,0.0,2.000000,1125.0,365

In [100]:
calendar_selected_features = [
    "calendar_availability_rate",
    "calendar_available_days",
    "calendar_avg_minimum_nights",
    "calendar_avg_maximum_nights",
    "calendar_observation_count"
]

print("SELECTED CALENDAR FEATURES")
print("=" * 60)

for feature in calendar_selected_features:
    print(
        "✓" if feature in calendar_features.columns else "✗",
        feature
    )

SELECTED CALENDAR FEATURES
============================================================
✓ calendar_availability_rate
✓ calendar_available_days
✓ calendar_avg_minimum_nights
✓ calendar_avg_maximum_nights
✓ calendar_observation_count

In [101]:
calendar_features.to_csv(
    os.path.join(
        PROCESSED_DATA_PATH,
        "calendar_feature_engineered.csv"
    ),
    index=False
)

print("Calendar feature-engineered dataset saved successfully.")

Calendar feature-engineered dataset saved successfully.

In [102]:
print(
    listings_clean["instant_bookable"].value_counts(
        dropna=False
    )
)

instant_bookable
NaN    490
Name: count, dtype: int64

## Reviews

In [120]:
# Create a copy
reviews_fe = reviews_clean.copy()

# Convert review date
reviews_fe["date"] = pd.to_datetime(
    reviews_fe["date"],
    errors="coerce"
)

print("Reviews shape:", reviews_fe.shape)
print("\nColumns:")
print(reviews_fe.columns.tolist())

Reviews shape: (29046, 6)

Columns:
['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments']

Feature 1 — Review Count

In [121]:
review_count = (
    reviews_fe
    .groupby("listing_id")
    .size()
    .reset_index(name="review_count")
)

Feature 2 — Review Period

In [122]:
review_dates = (
    reviews_fe
    .groupby("listing_id")["date"]
    .agg(
        first_review_date="min",
        last_review_date="max"
    )
    .reset_index()
)

review_dates["review_period_days"] = (
    review_dates["last_review_date"]
    - review_dates["first_review_date"]
).dt.days

review_period = review_dates[
    ["listing_id", "review_period_days"]
]

Feature 3 — Days Since Last Review

In [123]:
reference_date = reviews_fe["date"].max()

review_recency = review_dates[
    ["listing_id", "last_review_date"]
].copy()

review_recency["days_since_last_review"] = (
    reference_date -
    review_recency["last_review_date"]
).dt.days

review_recency = review_recency[
    ["listing_id", "days_since_last_review"]
]

Feature 4 — Reviews Per Month

In [124]:
reviews_per_month = review_dates.copy()

reviews_per_month["review_period_months"] = (
    reviews_per_month["review_period_days"] / 30
)

reviews_per_month["reviews_per_month_est"] = (
    reviews_fe.groupby("listing_id").size()
    .div(
        reviews_per_month
        .set_index("listing_id")["review_period_months"]
    )
)

reviews_per_month = (
    reviews_per_month
    .reset_index(drop=True)
    [["listing_id", "reviews_per_month_est"]]
)

In [126]:
reviews_per_month["reviews_per_month_est"] = (
    reviews_per_month["reviews_per_month_est"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)

Feature 5 — Recent Review Count

In [127]:
one_year_ago = reference_date - pd.Timedelta(days=365)

recent_review_count = (
    reviews_fe[
        reviews_fe["date"] >= one_year_ago
    ]
    .groupby("listing_id")
    .size()
    .reset_index(name="recent_review_count")
)

In [128]:
reviews_features = review_count.merge(
    review_period,
    on="listing_id",
    how="outer"
)

reviews_features = reviews_features.merge(
    review_recency,
    on="listing_id",
    how="outer"
)

reviews_features = reviews_features.merge(
    reviews_per_month,
    on="listing_id",
    how="outer"
)

reviews_features = reviews_features.merge(
    recent_review_count,
    on="listing_id",
    how="outer"
)

# Listings with no recent reviews should have 0
reviews_features["recent_review_count"] = (
    reviews_features["recent_review_count"]
    .fillna(0)
)

print("Reviews feature dataset shape:")
print(reviews_features.shape)

display(reviews_features.head(10))

Reviews feature dataset shape:
(430, 6)

,listing_id,review_count,review_period_days,days_since_last_review,reviews_per_month_est,recent_review_count
0,2992450,9,2969,1399,0.0,0.0
1,3820211,317,4181,142,0.0,8.0
2,5651579,406,4053,4,0.0,37.0
3,6623339,332,3676,351,0.0,1.0
4,9501054,469,3780,7,0.0,47.0
5,10768745,906,3769,15,0.0,103.0
6,11253948,227,3647,23,0.0,36.0
7,11639446,231,2830,838,0.0,0.0
8,12799126,29,1812,311,0.0,1.0
9,13083497,200,3635,2,0.0,11.0

In [129]:
review_selected_features = [
    "review_count",
    "review_period_days",
    "days_since_last_review",
    "reviews_per_month_est",
    "recent_review_count"
]

print("Missing values:")
print("=" * 60)

display(
    reviews_features[
        review_selected_features
    ].isna().sum()
)

Missing values:
============================================================

review_count              0
review_period_days        0
days_since_last_review    0
reviews_per_month_est     0
recent_review_count       0
dtype: int64

In [130]:
reviews_features[review_selected_features] = (
    reviews_features[review_selected_features]
    .fillna(0)
)

In [131]:
print(
    reviews_features[
        review_selected_features
    ].isna().sum()
)

review_count              0
review_period_days        0
days_since_last_review    0
reviews_per_month_est     0
recent_review_count       0
dtype: int64

In [132]:
print("FINAL REVIEWS FEATURES")
print("=" * 60)

display(
    reviews_features[
        ["listing_id"] + review_selected_features
    ].head(10)
)

FINAL REVIEWS FEATURES
============================================================

,listing_id,review_count,review_period_days,days_since_last_review,reviews_per_month_est,recent_review_count
0,2992450,9,2969,1399,0.0,0.0
1,3820211,317,4181,142,0.0,8.0
2,5651579,406,4053,4,0.0,37.0
3,6623339,332,3676,351,0.0,1.0
4,9501054,469,3780,7,0.0,47.0
5,10768745,906,3769,15,0.0,103.0
6,11253948,227,3647,23,0.0,36.0
7,11639446,231,2830,838,0.0,0.0
8,12799126,29,1812,311,0.0,1.0
9,13083497,200,3635,2,0.0,11.0

In [133]:
reviews_features.to_csv(
    os.path.join(
        PROCESSED_DATA_PATH,
        "reviews_feature_engineered.csv"
    ),
    index=False
)

print("Reviews feature-engineered dataset saved successfully.")

Reviews feature-engineered dataset saved successfully.

In [134]:
# ============================================
# DISPLAY ALL ENGINEERED FEATURES
# ============================================

listing_features = [
    "amenity_count",
    "is_entire_home",
    "is_superhost",
    "host_listing_count",
    "bathroom_bedroom_ratio"
]

calendar_features_list = [
    "calendar_availability_rate",
    "calendar_available_days",
    "calendar_avg_minimum_nights",
    "calendar_avg_maximum_nights",
    "calendar_observation_count"
]

review_features_list = [
    "review_count",
    "review_period_days",
    "days_since_last_review",
    "reviews_per_month_est",
    "recent_review_count"
]

# Create feature summary table
feature_table = pd.DataFrame({
    "Dataset": (
        ["Listings"] * 5 +
        ["Calendar"] * 5 +
        ["Reviews"] * 5
    ),
    "Feature": (
        listing_features +
        calendar_features_list +
        review_features_list
    )
})

# Add description
descriptions = {
    "amenity_count": "Number of amenities provided",
    "is_entire_home": "Whether the property is an entire home",
    "is_superhost": "Whether the host is a Superhost",
    "host_listing_count": "Number of listings managed by the host",
    "bathroom_bedroom_ratio": "Ratio of bathrooms to bedrooms",

    "calendar_availability_rate": "Proportion of observed dates available",
    "calendar_available_days": "Number of available calendar days",
    "calendar_avg_minimum_nights": "Average minimum nights requirement",
    "calendar_avg_maximum_nights": "Average maximum nights requirement",
    "calendar_observation_count": "Number of calendar observations",

    "review_count": "Total number of reviews",
    "review_period_days": "Days between first and last review",
    "days_since_last_review": "Days since the most recent review",
    "reviews_per_month_est": "Estimated reviews per month",
    "recent_review_count": "Reviews during the last 12 months"
}

feature_table["Description"] = feature_table["Feature"].map(descriptions)

# Display
print("ENGINEERED FEATURES — EXPERIMENT 2")
print("=" * 80)

display(feature_table)

ENGINEERED FEATURES — EXPERIMENT 2
================================================================================

,Dataset,Feature,Description
0,Listings,amenity_count,Number of amenities provided
1,Listings,is_entire_home,Whether the property is an entire home
2,Listings,is_superhost,Whether the host is a Superhost
3,Listings,host_listing_count,Number of listings managed by the host
4,Listings,bathroom_bedroom_ratio,Ratio of bathrooms to bedrooms
5,Calendar,calendar_availability_rate,Proportion of observed dates available
6,Calendar,calendar_available_days,Number of available calendar days
7,Calendar,calendar_avg_minimum_nights,Average minimum nights requirement
8,Calendar,calendar_avg_maximum_nights,Average maximum nights requirement
9,Calendar,calendar_observation_count,Number of calendar observations
10,Reviews,review_count,Total number of reviews
11,Reviews,review_period_days,Days between first and last review
12,Reviews,days_since_last_review,Days since the most recent review
13,Reviews,reviews_per_month_est,Estimated reviews per month
14,Reviews,recent_review_count,Reviews during the last 12 months