# Experiment 1: Case Study Framing and Dataset Preparation

## Project Title
Explainable Machine Learning System for Airbnb Listing Price Prediction and Fair Pricing Analysis

## Objective
To collect, load, inspect, validate, and document multiple Airbnb datasets that will later be cleaned, transformed, aggregated, and integrated for machine learning model development.

## Data Source
Inside Airbnb

## Selected Location
New York City

## Datasets
1. Detailed Listings Dataset
2. Calendar Dataset
3. Detailed Reviews Dataset

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

PROJECT_PATH = "/content/drive/MyDrive/ADS-Airbnb-Project"

RAW_DATA_PATH = os.path.join(PROJECT_PATH, "datasets", "raw")
PROCESSED_DATA_PATH = os.path.join(PROJECT_PATH, "datasets", "processed")
OUTPUT_TABLE_PATH = os.path.join(PROJECT_PATH, "outputs", "tables")
OUTPUT_FIGURE_PATH = os.path.join(PROJECT_PATH, "outputs", "figures")

print("Raw data path:", RAW_DATA_PATH)
print("Files available:")
print(os.listdir(RAW_DATA_PATH))

Raw data path: /content/drive/MyDrive/ADS-Airbnb-Project/datasets/raw
Files available:
['listings.csv.gz', 'calendar.csv.gz', 'reviews.csv.gz']

## Import Required Libraries

The libraries required for dataset loading, inspection, validation, and metadata preparation are imported.

In [ ]:
import pandas as pd
import numpy as np
import os

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [ ]:
LISTINGS_FILE = os.path.join(RAW_DATA_PATH, "listings.csv.gz")
CALENDAR_FILE = os.path.join(RAW_DATA_PATH, "calendar.csv.gz")
REVIEWS_FILE = os.path.join(RAW_DATA_PATH, "reviews.csv.gz")

In [ ]:
listings_df = pd.read_csv(LISTINGS_FILE)

calendar_df = pd.read_csv(CALENDAR_FILE)

reviews_df = pd.read_csv(REVIEWS_FILE)

In [ ]:
print("Listings loaded successfully:", listings_df.shape)
print("Calendar loaded successfully:", calendar_df.shape)
print("Reviews loaded successfully:", reviews_df.shape)

Listings loaded successfully: (490, 90)
Calendar loaded successfully: (178850, 5)
Reviews loaded successfully: (29046, 6)

In [ ]:
listings_df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_profile_id,host_profile_url,host_name,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,price_quote_raw,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2992450,https://www.airbnb.com/rooms/2992450,20260616211424,2026-06-16,city scrape,Luxury 2 bedroom apartment,The apartment is located in a quiet neighborho...,NaN,https://a0.muscache.com/pictures/44627226/0e72...,4621559,https://www.airbnb.com/users/show/4621559,1462661762635155041,https://www.airbnb.com/users/profile/146266176...,Kenneth,NaN,13,5,13,4,"New York, NY",I am a real down to earth & cool person.,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/users/4621559/profi...,NaN,1,NaN,NaN,t,t,NaN,THIRD WARD,NaN,42.65789,-73.75370,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Kitchen"", ""Essentials"", ""Heating"", ""Wifi"", ""...",$80.43,2027-03-31,2027-04-28,2252.0,80.43,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",28.0,1125.0,28.0,28.0,1125.0,1125.0,28.0,1125.0,NaN,t,0,0,0,77,2026-06-16,9,0,0,0,0,0,0.0,2014-07-01,2022-08-17,3.56,3.44,3.56,4.22,4.56,3.22,3.67,NaN,NaN,1,1,0,0,0.06
1,3820211,https://www.airbnb.com/rooms/3820211,20260616211424,2026-06-16,city scrape,Restored Precinct in Center Sq. w/Parking,Step into the charming and comfy 1BR/1BA apart...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,19648678,https://www.airbnb.com/users/show/19648678,1463087024016718788,https://www.airbnb.com/users/profile/146308702...,Ming,NaN,11,10,11,10,"Albany, NY","Hello! I’m a proud resident of Albany, NY, whe...",NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/pictures/user/User/...,NaN,7,NaN,NaN,t,t,NaN,SIXTH WARD,NaN,42.65222,-73.76724,Entire rental unit,Entire home/apt,3,1.0,1 bath,1.0,1.0,"[""Free washer \u2013 In unit"", ""Microwave"", ""S...",$211.00,2026-07-20,2026-07-21,211.0,211.00,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",1.0,1125.0,1.0,3.0,1125.0,1125.0,2.7,1125.0,NaN,t,0,23,53,328,2026-06-16,317,8,0,162,9,48,10128.0,2014-08-15,2026-01-25,4.75,4.88,4.87,4.85,4.81,4.82,4.78,NaN,NaN,7,7,0,0,2.20
2,5651579,https://www.airbnb.com/rooms/5651579,20260616211424,2026-06-16,city scrape,Large studio apt by Capital Center & ESP@,"Spacious studio with hardwood floors, fully eq...",NaN,https://a0.muscache.com/pictures/b3fc42f3-6e5e...,29288920,https://www.airbnb.com/users/show/29288920,1465431505328745177,https://www.airbnb.com/users/profile/146543150...,Gregg,NaN,11,3,11,3,"Albany, NY",I am an Albany native .I have lived in Ireland...,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/users/29288920/prof...,NaN,2,NaN,NaN,t,t,NaN,SECOND WARD,NaN,42.64615,-73.75966,Entire rental unit,Entire home/apt,2,1.0,1 bath,NaN,1.0,"[""Free washer \u2013 In unit"", ""Microwave"", ""S...",$97.00,2026-08-23,2026-08-24,97.0,97.00,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",1.0,1125.0,1.0,2.0,1125.0,1125.0,1.3,1125.0,NaN,t,2,3,25,25,2026-06-16,406,37,4,25,18,222,21534.0,2015-05-08,2026-06-12,4.52,4.62,4.44,4.81,4.87,4.75,4.63,NaN,NaN,2,1,1,0,3.00
3,6623339,https://www.airbnb.com/rooms/6623339,20260616211424,2026-06-16,city scrape,Center Sq. Loft in Converted Precinct w/ Parking,Step into the charming and comfy 1BR/1BA apart...,NaN,https://a0.muscache.com/pictures/prohost-api/H...,19648678,https://www.airbnb.com/users/show/19648678,1463087024016718788,https://www.airbnb.com/users/profile/146308702...,Ming,NaN,11,10,11,10,"Albany, NY","Hello! I’m a proud resident of Albany, NY, whe...",NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/pictures/user/User/...,NaN,7,NaN,NaN,t,t,NaN,SIXTH WARD,NaN,42.65222,-73.76724,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Microwave"", ""Stove"", ""Shower gel"", ""Coffee"",...",$160.00,2026-06-18,2026-06-19,160.0,160.00,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",1.0,1125.0,1.0,3.0,1125.0,1125.0,2.7,1125.0,NaN,t,27,54,84,359,2026-06-16,332,1,0,193,3,6,960.0,2015-06-07,2025-06-30,4.73,4.83,4.71,4.83,4.70,4.80,4.72,NaN,NaN,7,7,0,0,2.47
4,9501054,https://www.airbnb.com/rooms/9501054,20260616211424,2026-06-16,city scrape,Spacious suite with full bath by Capital Center,Great location within walking distance to the ...,NaN,https://a0.muscache.com/pictures/45153167-d704...,29288920,https://www.airbnb.com/users/show/29288920,1465431505328745177,https://www.airbnb.com/users/profile/146543150...,Gregg,NaN,11,3,11,3,"Albany, NY",I am an Albany native .I have lived in Ireland...,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/users/29288920/prof...,NaN,2,NaN,NaN,t,t,NaN,SECOND WARD,NaN,42.64734,-73.75851,Private room in rental unit,Private room,2,1.0,1 private bath,NaN,2.0,"[""Microwave"", ""Shower gel"", ""Long term stays a...",$86.00,2026-06-19,2026-06-20,86.0,86.00,"{""quote"": {""taxes"": null, ""currency"": ""USD"", ""...",1.0,1125.0,1.0,1.0,1125.0,1125.0,1.0,1125.0,NaN,t,23,35,55,235,2026-06-16,469,47,6,164,43,255,21930.0,2016-02-02,2026-06-09,4.58,4.73,4.53,4.84,4.87,4.77,4.68,NaN,NaN,2,1,1,0,3.71

In [ ]:
calendar_df.head()

   listing_id        date available  minimum_nights  maximum_nights
0     2992450  2026-06-16         f              28            1125
1     2992450  2026-06-17         f              28            1125
2     2992450  2026-06-18         f              28            1125
3     2992450  2026-06-19         f              28            1125
4     2992450  2026-06-20         f              28            1125

In [ ]:
reviews_df.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2992450,15066586,2014-07-01,16827297,Kristen,Large apartment; nice kitchen and bathroom. Ke...
1,2992450,21810844,2014-10-24,22648856,Christopher,"This may be a little late, but just to say Ken..."
2,2992450,27434334,2015-03-04,45406,Altay,The apartment was very clean and convenient to...
3,2992450,28524578,2015-03-25,5485362,John,Kenneth was ready when I got there and arrange...
4,2992450,35913434,2015-06-23,15772025,Jennifer,We were pleased to see how 2nd Street and the ...

In [ ]:
dataset_inventory = pd.DataFrame({
    "Dataset": [
        "Listings",
        "Calendar",
        "Reviews"
    ],

    "Rows": [
        listings_df.shape[0],
        calendar_df.shape[0],
        reviews_df.shape[0]
    ],

    "Columns": [
        listings_df.shape[1],
        calendar_df.shape[1],
        reviews_df.shape[1]
    ],

    "Granularity": [
        "One row per listing",
        "One row per listing-date",
        "One row per review"
    ]
})

dataset_inventory

    Dataset    Rows  Columns               Granularity
0  Listings     490       90       One row per listing
1  Calendar  178850        5  One row per listing-date
2   Reviews   29046        6        One row per review

In [ ]:
inventory_file = os.path.join(
    OUTPUT_TABLE_PATH,
    "exp1_dataset_inventory.csv"
)

dataset_inventory.to_csv(inventory_file, index=False)

print("Dataset inventory saved.")

Dataset inventory saved.

In [ ]:
print("LISTINGS COLUMNS")
print(listings_df.columns.tolist())

LISTINGS COLUMNS
['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months', 'hosts_time_as_host_years', 'hosts_time_as_host_months', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'price_quote_checkin_date', 'price_quote_checkout_date', 'price_quote_total_price', 'price_quote_price_per_night', 'price_quote_raw', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month']

In [ ]:
print("CALENDAR COLUMNS")
print(calendar_df.columns.tolist())

CALENDAR COLUMNS
['listing_id', 'date', 'available', 'minimum_nights', 'maximum_nights']

In [ ]:
print("REVIEWS COLUMNS")
print(reviews_df.columns.tolist())

REVIEWS COLUMNS
['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments']

In [ ]:
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            490 non-null    int64
 1   listing_url                                   490 non-null    object
 2   scrape_id                                     490 non-null    int64
 3   last_scraped                                  490 non-null    object
 4   source                                        490 non-null    object
 5   name                                          490 non-null    object
 6   description                                   481 non-null    object
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   490 non-null    object
 9   host_id                                       490 non-null    int64
 10  host_url                                      490 non-null    object
 11  host_profile_id                               490 non-null    int64
 12  host_profile_url                              490 non-null    object
 13  host_name                                     490 non-null    object
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      490 non-null    int64
 16  hosts_time_as_user_months                     490 non-null    int64
 17  hosts_time_as_host_years                      490 non-null    int64
 18  hosts_time_as_host_months                     490 non-null    int64
 19  host_location                                 348 non-null    object
 20  host_about                                    260 non-null    object
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             490 non-null    object
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              490 non-null    object
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           490 non-null    int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          490 non-null    object
 32  host_identity_verified                        490 non-null    object
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        490 non-null    object
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      490 non-null    float64
 37  longitude                                     490 non-null    float64
 38  property_type                                 490 non-null    object
 39  room_type                                     490 non-null    object
 40  accommodates                                  490 non-null    int64
 41  bathrooms                                     445 non-null    float64
 42  bathrooms_text                                486 non-null    object
 43  bedrooms                                      378 non-null    float64
 44  beds                                          446 non-null    float64
 45  amenities                                     490 non-null    object
 46  price                                         458 non-null    object
 47  price_quote_checkin_date                      468 non-null    object
 48  price_quote_checkout_date                     468 non-null    object
 49  price_quote_total_price                       458 non-null    float64
 50  price_quote_price_per_night                   458 non-null    float64
 51  price_quote_raw                               468 non-null    object
 52  minimum_nights                                489 non-null    float64
 53  maximum_nights                                489 non-null    float64
 54  minimum_minimum_nights                        489 non-null    float64
 55  maximum_minimum_nights                        489 non-null    float64
 56  minimum_maximum_nights                        489 non-null    float64
 57  maximum_maximum_nights                        489 non-null    float64
 58  minimum_nights_avg_ntm                        490 non-null    float64
 59  maximum_nights_avg_ntm                        490 non-null    float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              485 non-null    object
 62  availability_30                               490 non-null    int64
 63  availability_60                               490 non-null    int64
 64  availability_90                               490 non-null    int64
 65  availability_365                              490 non-null    int64
 66  calendar_last_scraped                         490 non-null    object
 67  number_of_reviews                             490 non-null    int64
 68  number_of_reviews_ltm                         490 non-null    int64
 69  number_of_reviews_l30d                        490 non-null    int64
 70  availability_eoy                              490 non-null    int64
 71  number_of_reviews_ly                          490 non-null    int64
 72  estimated_occupancy_l365d                     490 non-null    int64
 73  estimated_revenue_l365d                       458 non-null    float64
 74  first_review                                  430 non-null    object
 75  last_review                                   430 non-null    object
 76  review_scores_rating                          430 non-null    float64
 77  review_scores_accuracy                        430 non-null    float64
 78  review_scores_cleanliness                     430 non-null    float64
 79  review_scores_checkin                         430 non-null    float64
 80  review_scores_communication                   430 non-null    float64
 81  review_scores_location                        430 non-null    float64
 82  review_scores_value                           430 non-null    float64
 83  license                                       0 non-null      float64
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                490 non-null    int64
 86  calculated_host_listings_count_entire_homes   490 non-null    int64
 87  calculated_host_listings_count_private_rooms  490 non-null    int64
 88  calculated_host_listings_count_shared_rooms   490 non-null    int64
 89  reviews_per_month                             430 non-null    float64
dtypes: float64(38), int64(24), object(28)
memory usage: 344.7+ KB

In [ ]:
calendar_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178850 entries, 0 to 178849
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   listing_id      178850 non-null  int64
 1   date            178850 non-null  object
 2   available       178850 non-null  object
 3   minimum_nights  178850 non-null  int64
 4   maximum_nights  178850 non-null  int64
dtypes: int64(3), object(2)
memory usage: 6.8+ MB

In [ ]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29046 entries, 0 to 29045
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   listing_id     29046 non-null  int64
 1   id             29046 non-null  int64
 2   date           29046 non-null  object
 3   reviewer_id    29046 non-null  int64
 4   reviewer_name  29046 non-null  object
 5   comments       29038 non-null  object
dtypes: int64(3), object(3)
memory usage: 1.3+ MB

In [ ]:
def memory_usage_mb(df):
    return df.memory_usage(deep=True).sum() / (1024 ** 2)

print("Listings Memory Usage:",
      round(memory_usage_mb(listings_df), 2), "MB")

print("Calendar Memory Usage:",
      round(memory_usage_mb(calendar_df), 2), "MB")

print("Reviews Memory Usage:",
      round(memory_usage_mb(reviews_df), 2), "MB")

Listings Memory Usage: 2.11 MB
Calendar Memory Usage: 22.69 MB
Reviews Memory Usage: 14.39 MB

Step 11 — Verify the integration keys

Check the listings identifier:

In [ ]:
print("Listings contains 'id':", "id" in listings_df.columns)

Listings contains 'id': True

Check foreign keys:

In [ ]:
print(
    "Calendar contains 'listing_id':",
    "listing_id" in calendar_df.columns
)

print(
    "Reviews contains 'listing_id':",
    "listing_id" in reviews_df.columns
)

Calendar contains 'listing_id': True
Reviews contains 'listing_id': True

Now verify uniqueness:

In [ ]:
print("Listings rows:", len(listings_df))

print(
    "Unique listing IDs:",
    listings_df["id"].nunique()
)

print(
    "Duplicate listing IDs:",
    listings_df["id"].duplicated().sum()
)

Listings rows: 490
Unique listing IDs: 490
Duplicate listing IDs: 0

In [ ]:
print(
    "Unique listings represented in Calendar:",
    calendar_df["listing_id"].nunique()
)

print(
    "Unique listings represented in Reviews:",
    reviews_df["listing_id"].nunique()
)

Unique listings represented in Calendar: 490
Unique listings represented in Reviews: 430

Step 12 — Check referential integrity

In [ ]:
listing_ids = set(listings_df["id"])

calendar_ids = set(calendar_df["listing_id"])

review_ids = set(reviews_df["listing_id"])

In [ ]:
calendar_unmatched = calendar_ids - listing_ids

review_unmatched = review_ids - listing_ids

print(
    "Calendar listing IDs absent from Listings:",
    len(calendar_unmatched)
)

print(
    "Review listing IDs absent from Listings:",
    len(review_unmatched)
)

Calendar listing IDs absent from Listings: 0
Review listing IDs absent from Listings: 0

Step 13 — Check exact duplicate rows

In [ ]:
print(
    "Listings exact duplicate rows:",
    listings_df.duplicated().sum()
)

print(
    "Calendar exact duplicate rows:",
    calendar_df.duplicated().sum()
)

print(
    "Reviews exact duplicate rows:",
    reviews_df.duplicated().sum()
)

Listings exact duplicate rows: 0
Calendar exact duplicate rows: 0
Reviews exact duplicate rows: 0

Step 14 — Perform an initial missing-value assessment

In [ ]:
def missing_value_summary(df):

    missing_count = df.isnull().sum()

    missing_percentage = (
        missing_count / len(df)
    ) * 100

    summary = pd.DataFrame({
        "Missing_Count": missing_count,
        "Missing_Percentage": missing_percentage
    })

    summary = summary[
        summary["Missing_Count"] > 0
    ]

    return summary.sort_values(
        by="Missing_Percentage",
        ascending=False
    )

In [ ]:
listings_missing = missing_value_summary(listings_df)

listings_missing.head(20)

                              Missing_Count  Missing_Percentage
neighborhood_overview                   490          100.000000
host_since                              490          100.000000
host_acceptance_rate                    490          100.000000
host_response_rate                      490          100.000000
host_response_time                      490          100.000000
host_neighbourhood                      490          100.000000
host_total_listings_count               490          100.000000
host_verifications                      490          100.000000
host_thumbnail_url                      490          100.000000
neighbourhood                           490          100.000000
instant_bookable                        490          100.000000
license                                 490          100.000000
neighbourhood_group_cleansed            490          100.000000
calendar_updated                        490          100.000000
host_about                              230           46.938776
host_location                           142           28.979592
bedrooms                                112           22.857143
first_review                             60           12.244898
review_scores_checkin                    60           12.244898
review_scores_cleanliness                60           12.244898

In [ ]:
calendar_missing = missing_value_summary(calendar_df)

calendar_missing

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

In [ ]:
reviews_missing = missing_value_summary(reviews_df)

reviews_missing

          Missing_Count  Missing_Percentage
comments              8            0.027543

In [ ]:
listings_missing.to_csv(
    os.path.join(
        OUTPUT_TABLE_PATH,
        "exp1_listings_missing_values.csv"
    )
)

calendar_missing.to_csv(
    os.path.join(
        OUTPUT_TABLE_PATH,
        "exp1_calendar_missing_values.csv"
    )
)

reviews_missing.to_csv(
    os.path.join(
        OUTPUT_TABLE_PATH,
        "exp1_reviews_missing_values.csv"
    )
)

Step 15 — Inspect the target variable - price

In [ ]:
listings_df["price"].head(10)

0     $80.43
1    $211.00
2     $97.00
3    $160.00
4     $86.00
5     $58.00
6    $277.31
7     $62.87
8     $64.00
9    $313.00
Name: price, dtype: object

In [ ]:
print(listings_df["price"].dtype)

object

Step 16 — Check basic cardinality

In [ ]:
important_categorical_columns = [
    "neighbourhood_cleansed",
    "property_type",
    "room_type"
]

for column in important_categorical_columns:

    print(column)

    print(
        "Unique values:",
        listings_df[column].nunique()
    )

    print()

neighbourhood_cleansed
Unique values: 15

property_type
Unique values: 21

room_type
Unique values: 4

In [ ]:
listings_df["room_type"].value_counts(dropna=False)

room_type
Entire home/apt    345
Private room       135
Hotel room           9
Shared room          1
Name: count, dtype: int64

In [ ]:
listings_df["property_type"].value_counts(dropna=False).head(20)

property_type
Entire rental unit                   255
Private room in home                  78
Entire home                           67
Private room in rental unit           35
Room in hotel                         19
Entire condo                           6
Entire townhouse                       6
Private room in bed and breakfast      5
Private room in guest suite            3
Entire guest suite                     3
Entire loft                            2
Private room in townhouse              2
Entire place                           1
Entire cottage                         1
Entire vacation home                   1
Room in aparthotel                     1
Shared room in bed and breakfast       1
Entire guesthouse                      1
Private room in villa                  1
Private room in guesthouse             1
Name: count, dtype: int64

In [ ]:
listings_df["neighbourhood_cleansed"].value_counts(dropna=False).head(20)

neighbourhood_cleansed
SIXTH WARD         117
TENTH WARD          56
THIRD WARD          43
NINTH WARD          42
SECOND WARD         41
THIRTEENTH WARD     41
FOURTEENTH WARD     32
ELEVENTH WARD       32
FOURTH WARD         15
FIFTEENTH WARD      14
FIFTH WARD          14
SEVENTH WARD        14
EIGHTH WARD         13
FIRST WARD          12
TWELFTH WARD         4
Name: count, dtype: int64

Step 17 — Create a schema summary automatically

In [ ]:
def create_schema_summary(df, dataset_name):

    return pd.DataFrame({
        "Dataset": dataset_name,
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values,
        "Non_Null_Count": df.notnull().sum().values,
        "Missing_Count": df.isnull().sum().values,
        "Unique_Values": df.nunique(dropna=True).values
    })

In [ ]:
listings_schema = create_schema_summary(
    listings_df,
    "Listings"
)

calendar_schema = create_schema_summary(
    calendar_df,
    "Calendar"
)

reviews_schema = create_schema_summary(
    reviews_df,
    "Reviews"
)

In [ ]:
complete_schema = pd.concat(
    [
        listings_schema,
        calendar_schema,
        reviews_schema
    ],
    ignore_index=True
)

complete_schema.head()

,Dataset,Column,Data_Type,Non_Null_Count,Missing_Count,Unique_Values
0,Listings,id,int64,490,0,490
1,Listings,listing_url,object,490,0,490
2,Listings,scrape_id,int64,490,0,1
3,Listings,last_scraped,object,490,0,2
4,Listings,source,object,490,0,2

In [ ]:
complete_schema.to_csv(
    os.path.join(
        OUTPUT_TABLE_PATH,
        "exp1_complete_schema_summary.csv"
    ),
    index=False
)

Step 18 — Document the integration strategy

## Dataset Integration Strategy

The Listings dataset will act as the master dataset because it contains one record per Airbnb listing.

The Calendar dataset has multiple records per listing because availability and price information are recorded for individual dates. Therefore, Calendar data cannot be directly merged with Listings. It will first be aggregated using `listing_id` to create listing-level features.

The Reviews dataset also contains multiple records per listing. It will be aggregated using `listing_id` to generate review activity and, where appropriate, sentiment-based features.

After aggregation, both datasets will contain one row per `listing_id` and can be merged with the Listings dataset.

Planned integration:

Listings
    +
Aggregated Calendar Features
    +
Aggregated Review Features
    ↓
Final Integrated Airbnb Dataset

Step 19 — Create a data quality observations table

In [ ]:
quality_observations = pd.DataFrame({
    "Issue": [
        "Missing values",
        "Price stored as text",
        "One-to-many dataset relationships",
        "Large calendar dataset",
        "High-cardinality categorical variables",
        "Potential unmatched listing IDs",
        "Potential target leakage"
    ],

    "Dataset": [
        "Listings / Calendar / Reviews",
        "Listings",
        "Calendar and Reviews",
        "Calendar",
        "Listings",
        "Calendar and Reviews",
        "Calendar"
    ],

    "Planned_Action": [
        "Analyze and handle in Experiment 2",
        "Convert price to numeric format",
        "Aggregate before merging",
        "Use memory-efficient processing",
        "Apply appropriate encoding or feature grouping",
        "Investigate before integration",
        "Exclude calendar-derived features that directly reveal the prediction target"
    ]
})

quality_observations

,Issue,Dataset,Planned_Action
0,Missing values,Listings / Calendar / Reviews,Analyze and handle in Experiment 2
1,Price stored as text,Listings,Convert price to numeric format
2,One-to-many dataset relationships,Calendar and Reviews,Aggregate before merging
3,Large calendar dataset,Calendar,Use memory-efficient processing
4,High-cardinality categorical variables,Listings,Apply appropriate encoding or feature grouping
5,Potential unmatched listing IDs,Calendar and Reviews,Investigate before integration
6,Potential target leakage,Calendar,Exclude calendar-derived features that directl...

In [ ]:
quality_observations.to_csv(
    os.path.join(
        OUTPUT_TABLE_PATH,
        "exp1_data_quality_observations.csv"
    ),
    index=False
)

Step 20 — Install DVC

## Data Versioning using DVC

DVC (Data Version Control) is used to version and manage the raw Airbnb datasets without storing large dataset files directly in the Git repository.

In [2]:
!pip install -q dvc

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 470.1/470.1 kB 24.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 451.2/451.2 kB 32.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.5/155.5 kB 15.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.2/214.2 kB 18.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 10.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.2/74.2 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 66.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.2/381.2 kB 29.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.1/87.1 kB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 6.1 MB/s eta 0:00:00

In [3]:
!dvc --version

3.67.1

Step 21 — Move to the project directory

In [4]:
%cd "/content/drive/MyDrive/ADS-Airbnb-Project"

/content/drive/MyDrive/ADS-Airbnb-Project

In [5]:
!pwd

/content/drive/MyDrive/ADS-Airbnb-Project

In [6]:
!ls

datasets  notebooks  outputs  reports

Step 22 — Initialize Git

In [ ]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/drive/MyDrive/ADS-Airbnb-Project/.git/

In [7]:
!git status

Refresh index: 100% (12/12), done.
On branch main
nothing to commit, working tree clean

In [ ]:
!git config user.name "CloudyPatil"
!git config user.email "harshalgenai@gmail.com"

In [8]:
!dvc status

Data and pipelines are up to date.

Step 23 — Initialize DVC

In [ ]:
!dvc init

Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/treeverse/dvc>

In [ ]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .dvc/.gitignore
	new file:   .dvc/config
	new file:   .dvcignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	datasets/
	outputs/

Step 24 — Track the raw dataset folder with DVC

In [ ]:
!dvc add datasets/raw

⠋ Checking graph
Adding...:   0% 0/1 [00:00<?, ?file/s{'info': ''}]
!
          |0.00 [00:00,     ?file/s]
 17% 1.00/6.00 [00:01<00:07, 1.41s/file{'info': ''}]
 33% 2.00/6.00 [00:02<00:03, 1.01file/s{'info': ''}]
 50% 3.00/6.00 [00:02<00:02, 1.06file/s{'info': ''}]
 67% 4.00/6.00 [00:03<00:01, 1.15file/s{'info': ''}]
 83% 5.00/6.00 [00:04<00:00, 1.11file/s{'info': ''}]
100% 6.00/6.00 [00:05<00:00, 1.09file/s{'info': ''}]

!
  0% |          |0/? [00:00<?,    ?files/s]

Adding datasets/raw to cache:   0% 0/6 [00:00<?, ?file/s]
Adding datasets/raw to cache:   0% 0/6 [00:00<?, ?file/s{'info': ''}]
Adding datasets/raw to cache:  33% 2/6 [00:00<00:00, 13.06file/s{'info': ''}]
Adding datasets/raw to cache:  67% 4/6 [00:00<00:00, 12.18file/s{'info': ''}]

!
          |0.00 [00:00,    ?files/s]
Adding...: 100% 1/1 [00:06<00:00,  6.27s/file{'info': ''}]

To track the changes with git, run:

	git add datasets/.gitignore datasets/raw.dvc

To enable auto staging, run:

	dvc config core.autostage true

In [ ]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .dvc/.gitignore
	new file:   .dvc/config
	new file:   .dvcignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	datasets/
	outputs/

Step 25 — Configure Google Drive as the DVC remote

In [ ]:
!dvc remote add -d myremote "/content/drive/MyDrive/ADS-Airbnb-DVC-Storage"

Setting 'myremote' as a default remote.

In [ ]:
!dvc remote list

myremote        /content/drive/MyDrive/ADS-Airbnb-DVC-Storage   (default)

Step 26 — Push the raw datasets to the DVC remote

In [ ]:
!dvc push

Collecting          |7.00 [00:00,  120entry/s]
Pushing
Querying remote cache:   0% 0/1 [00:00<?, ?files/s]
Querying remote cache:   0% 0/1 [00:00<?, ?files/s{'info': ''}]

!
  0% |          |0/? [00:00<?,    ?files/s]

!
  0% |          |0/? [00:00<?,    ?files/s]

Pushing to local:   0% 0/7 [00:00<?, ?file/s]
Pushing to local:   0% 0/7 [00:00<?, ?file/s{'info': ''}]
Pushing to local:  33% 2/6 [00:00<00:00, 17.29file/s{'info': ''}]
Pushing to local:  67% 4/6 [00:00<00:00, 16.14file/s{'info': ''}]
  0%|          |Pushing to local                  6/? [00:00<00:00, 17.01file/s]
Pushing
7 files pushed

Step 27 — Create a .gitignore

In [ ]:
%%writefile .gitignore
.ipynb_checkpoints/
__pycache__/
*.pyc
.DS_Store

Writing .gitignore

In [ ]:
!cat datasets/.gitignore

/raw

Step 28 — Commit the Experiment 1 project files

In [ ]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .dvc/.gitignore
	new file:   .dvc/config
	new file:   .dvcignore

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .dvc/config

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore
	datasets/
	outputs/

In [ ]:
!git add .dvc .dvcignore .gitignore datasets/raw.dvc datasets/.gitignore

In [ ]:
!git add notebooks outputs

In [ ]:
!git status

On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   .dvc/.gitignore
	new file:   .dvc/config
	new file:   .dvcignore
	new file:   .gitignore
	new file:   datasets/.gitignore
	new file:   datasets/raw.dvc
	new file:   outputs/tables/exp1_calendar_missing_values.csv
	new file:   outputs/tables/exp1_complete_schema_summary.csv
	new file:   outputs/tables/exp1_data_quality_observations.csv
	new file:   outputs/tables/exp1_dataset_inventory.csv
	new file:   outputs/tables/exp1_listings_missing_values.csv
	new file:   outputs/tables/exp1_reviews_missing_values.csv

In [ ]:
!git commit -m "Complete Experiment 1 dataset preparation and DVC setup"

[master (root-commit) 8bebc28] Complete Experiment 1 dataset preparation and DVC setup
 12 files changed, 184 insertions(+)
 create mode 100644 .dvc/.gitignore
 create mode 100644 .dvc/config
 create mode 100644 .dvcignore
 create mode 100644 .gitignore
 create mode 100644 datasets/.gitignore
 create mode 100644 datasets/raw.dvc
 create mode 100644 outputs/tables/exp1_calendar_missing_values.csv
 create mode 100644 outputs/tables/exp1_complete_schema_summary.csv
 create mode 100644 outputs/tables/exp1_data_quality_observations.csv
 create mode 100644 outputs/tables/exp1_dataset_inventory.csv
 create mode 100644 outputs/tables/exp1_listings_missing_values.csv
 create mode 100644 outputs/tables/exp1_reviews_missing_values.csv

Step 29 — Create the GitHub repository

Step 30 — Connect the local repository to GitHub

In [ ]:
!git branch -M main

In [ ]:
!git remote add origin https://github.com/CloudyPatil/ADS-Airbnb-Price-Prediction.git

In [9]:
!git remote -v

origin	https://github.com/CloudyPatil/ADS-Airbnb-Price-Prediction.git (fetch)
origin	https://github.com/CloudyPatil/ADS-Airbnb-Price-Prediction.git (push)

In [10]:
!git status

On branch main
nothing to commit, working tree clean

In [ ]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address

In [11]:
import getpass

username = input("GitHub Username: ")
token = getpass.getpass("GitHub Token: ")

GitHub Username: CloudyPatil
GitHub Token: ··········

In [12]:
repo = "ADS-Airbnb-Price-Prediction"

url = f"https://{username}:{token}@github.com/{username}/{repo}.git"

!git remote set-url origin {url}

In [13]:
!git remote -v

origin	https://CloudyPatil:REMOVED_GITHUB_TOKEN@github.com/CloudyPatil/ADS-Airbnb-Price-Prediction.git (fetch)
origin	https://CloudyPatil:REMOVED_GITHUB_TOKEN@github.com/CloudyPatil/ADS-Airbnb-Price-Prediction.git (push)

In [14]:
!git remote set-url origin https://github.com/CloudyPatil/ADS-Airbnb-Price-Prediction.git

In [15]:
!git remote -v

origin	https://github.com/CloudyPatil/ADS-Airbnb-Price-Prediction.git (fetch)
origin	https://github.com/CloudyPatil/ADS-Airbnb-Price-Prediction.git (push)

In [16]:
!git status

On branch main
nothing to commit, working tree clean

In [17]:
!git branch

* main

In [18]:
!git push -u origin main

fatal: could not read Username for 'https://github.com': No such device or address

In [19]:
import getpass

username = input("GitHub Username: ")
token = getpass.getpass("GitHub Personal Access Token: ")

GitHub Username: CloudyPatil
GitHub Personal Access Token: ··········

In [20]:
repo = "ADS-Airbnb-Price-Prediction"

!git push https://{username}:{token}@github.com/{username}/{repo}.git main

Enumerating objects: 18, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 2 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (18/18), 3.37 KiB | 63.00 KiB/s, done.
Total 18 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/CloudyPatil/ADS-Airbnb-Price-Prediction.git
 * [new branch]      main -> main

In [21]:
!dvc status

Data and pipelines are up to date.

In [22]:
!ls datasets

processed  raw	raw.dvc